stages:
  - analysis
  - test

pylint:
  stage: analysis
  image: python:3.8
  before_script:
    - pip install pylint pylint-exit anybadge
  script:
    - mkdir ./pylint
    - find . -type f -name "*.py" -not -path "*/venv/*" | xargs pylint --rcfile=static_config/pylint-rc.ini | tee ./pylint/pylint.log || pylint-exit $? --error-fail
    - PYLINT_SCORE=$(sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' ./pylint/pylint.log)
    - anybadge --label=Pylint --file=pylint/pylint.svg --value=$PYLINT_SCORE 2=red 4=orange 8=yellow 10=green
    - echo "Pylint score is $PYLINT_SCORE"
    - if [[ "${PYLINT_SCORE%.*}" -lt "7" ]]; then exit 1; fi
  artifacts:
    paths:
      - ./pylint/
    expire_in: 1 day
  only:
    - merge_requests
    - schedules
    - master
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /no-pylint/

